
parameters:
- name: AzureDevOpsPat
  type: string
  default: ''
- name: GitHubPat
  type: string
  default: ''
- name: GitHubOwner
  type: string
  default: ''
- name: GitHubRepo
  type: string
  default: ''
- name: Branch
  type: string
  default: ''

jobs:
  - template: /eng/pipelines/common/content-validation-for-javascript.yml
    parameters:
      PackageName: 'azure-cognitiveservices-customvision-training'
      CsvPackageName: '@azure/cognitiveservices-customvision-training'
      ReadmeName: 'cognitiveservices/customvisiontraining'
      jobDisplayName: 'AZURE_COGNITIVESERVICES_CUSTOMVISION_TRAINING'
      DotNetSdkVersion: '8.0.x'
      GitHubPat: ${{ parameters.GitHubPat }}
      GitHubOwner: ${{ parameters.GitHubOwner }}
      GitHubRepo: ${{ parameters.GitHubRepo }}
      AzureDevOpsPat: ${{ parameters.AzureDevOpsPat }}
      Branch: ${{ parameters.Branch }}
