parameters:
- name: AzureDevOpsPat
  type: string
  default: ''
- name: GitHubPat
  type: string
  default: ''
- name: GitHubOwner
  type: string
  default: ''
- name: GitHubRepo
  type: string
  default: ''
- name: Branch
  type: string
  default: ''
- name: packages
  type: string
  default: 'azure-ai-content-safety-rest, azure-ai-document-intelligence, azure-ai-form-recognizer, azure-ai-language-text, azure-ai-text-analytics, azure-ai-translation-document, azure-ai-translation-text, azure-app-configuration, azure-attestation, azure-cognitiveservices-autosuggest, azure-cognitiveservices-computervision, azure-cognitiveservices-contentmoderator, azure-cognitiveservices-customimagesearch, azure-cognitiveservices-customsearch, azure-cognitiveservices-customvision-prediction, azure-cognitiveservices-customvision-training, azure-cognitiveservices-entitysearch, azure-cognitiveservices-face, azure-cognitiveservices-imagesearch, azure-cognitiveservices-localsearch, azure-cognitiveservices-luis-runtime, azure-cognitiveservices-newssearch, azure-cognitiveservices-personalizer, azure-cognitiveservices-qnamaker-runtime, azure-cognitiveservices-qnamaker, azure-cognitiveservices-spellcheck, azure-cognitiveservices-videosearch, azure-cognitiveservices-visualsearch, azure-cognitiveservices-websearch, azure-communication-call-automation, azure-communication-calling-effects, azure-communication-chat, azure-communication-common, azure-communication-email, azure-communication-identity, azure-communication-messages, azure-communication-phone-numbers, azure-communication-rooms, azure-communication-sms, azure-confidential-ledger, azure-container-registry, azure-core, azure-cosmos, azure-data-tables, azure-developer-devcenter, azure-digital-twins-core, azure-durablefunctions, azure-event-hubs, azure-eventgrid-namespaces, azure-eventhubs-checkpointstore-blob, azure-functions, azure-identity-broker, azure-identity-cache-persistence, azure-identity-vscode, azure-identity, azure-iot-common, azure-iot-device-update, azure-iot-device, azure-iot-digitaltwins-service, azure-iot-provisioning-device, azure-iot-provisioning-service, azure-iothub, azure-keyvault-administration, azure-keyvault-certificates, azure-keyvault-common, azure-keyvault-keys, azure-keyvault-secrets, azure-load-testing, azure-microsoft-cognitiveservices-speech-sdk, azure-monitor-ingestion, azure-monitor-opentelemetry, azure-monitor-query, azure-msrest, azure-notification-hubs, azure-schema-registry-avro, azure-schema-registry-json, azure-schema-registry, azure-service-bus, azure-storage-file-datalake, azure-storage-file-share, azure-storage-queue, azure-uncategorizedpackages, azure-web-pubsub-client, azure-web-pubsub'
  
jobs:
- ${{ each packageName in split(parameters.packages, ',') }}:
  - template: /eng/pipelines/javascript/package/${{ packageName }}.yml
    parameters:
      GitHubPat: ${{ parameters.GitHubPat }}
      GitHubOwner: ${{ parameters.GitHubOwner }}
      GitHubRepo: ${{ parameters.GitHubRepo }}
      AzureDevOpsPat: ${{ parameters.AzureDevOpsPat }}
      Branch: ${{ parameters.Branch }}
