# /eng/pipelines/templates/generate-matrix-from-json.yml
parameters:
  packagesJson: ''

jobs:
- ${{ each pkg in fromJson(parameters.packagesJson) }}:
  - job: validate_${{ pkg.packageName }}
    displayName: Validate ${{ pkg.packageName }}
    variables:
      packageName: ${{ pkg.packageName }}
      readmeName: ${{ coalesce(pkg.readmeName, format('{0}-readme', replace(pkg.packageName, 'azure-', ''))) }}
    steps:
    - template: /eng/pipelines/common/content-validation-for-python.yml
      parameters:
        PackageName: $(packageName)
        ReadmeName: $(readmeName)
        DotNetSdkVersion: '8.0.x'
        AzureDevOpsPat: $(AZURE_DEVOPS_PAT)
        GitHubPat: $(GITHUB_PAT)
        GitHubOwner: $(GITHUB_OWNER)
        GitHubRepo: $(GITHUB_REPO)
        Branch: ${{ parameters.branch }}