name: Run switched packages content validation for python
trigger: none

parameters:
- name: packages
  displayName: |
      Comma-delimited list of packages to test against (by default, 'all' to run all). Example: 'azure-appconfiguration, azure-keyvault-keys'
  type: string
  default: 'all'

- name: branch
  displayName: |
      You can choose the review version of the page for testing, and you need to select the corresponding branch. Example: 'nickwalk/yaml-changes'
  type: string
  default: 'main'

variables:
  pipelineRunLink: $[ format('https://dev.azure.com/{0}/{1}/_build/results?buildId={2}&view=results', variables['System.CollectionUri'].split('/')[4], variables['System.TeamProject'], variables['System.Build.BuildId']) ]
 

stages:
- stage: ContentValidationTesting
  jobs:
  - ${{ each packageName in split(parameters.packages, ',') }}:
    - ${{ if ne(parameters.packages, 'all') }}:
      - template: /eng/pipelines/python/package/${{ packageName }}.yml
        parameters:
          AzureDevOpsPat: $(AZURE_DEVOPS_PAT)
          GitHubPat: $(GITHUB_PAT)
          GitHubOwner: $(GITHUB_OWNER)
          GitHubRepo: $(GITHUB_REPO)
          Branch: ${{ parameters.Branch }}

  - ${{ if eq(parameters.packages, 'all') }}:
    - template: /eng/pipelines/python/package/run-all-packages.yml
      parameters:
        AzureDevOpsPat: $(AZURE_DEVOPS_PAT)
        GitHubPat: $(GITHUB_PAT)
        GitHubOwner: $(GITHUB_OWNER)
        GitHubRepo: $(GITHUB_REPO)
        Branch: ${{ parameters.Branch }}
  
  # - template: /eng/pipelines/common/content-validation-special-cases.yml
  #   parameters:
  #     DotNetSdkVersion: '8.0.x'

- stage: TotalIssuesSummary
  condition: always()
  jobs:
  - job: Maintain_Total_Issues_List
    displayName: Maintain_Total_Issues_List
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: DownloadPipelineArtifact@2
      displayName: Download The Last Artifact history-issues-summary
      inputs:
        buildType: 'specific'
        project: 'content-validation-automation'
        pipeline: 'Content Validation For Python'
        buildVersionToDownload: 'latestFromBranch'
        allowPartiallySucceededBuilds: true
        allowFailedBuilds: false
        branchName: 'refs/heads/main'
        artifactName: 'issues-summary'
        downloadPath: '$(System.DefaultWorkingDirectory)/Artifacts'
      continueOnError: true

    - task: DownloadPipelineArtifact@2
      displayName: Download The Current Artifact 
      inputs:
        buildType: 'current'
        downloadPath: '$(System.DefaultWorkingDirectory)/Artifacts'

    - task: DotNetCoreCLI@2
      displayName: Build issuer helper project
      inputs:
        command: 'build'
        projects: 'IssuerHelper/IssuerHelper.csproj'

    - task: DotNetCoreCLI@2
      displayName: Summary Total Issues of all packages
      env:
        PackageName: ${{ parameters.packages }}
        PipelineRunLink: $(pipelineRunLink)
      inputs:
        command: 'run'
        workingDirectory: '$(System.DefaultWorkingDirectory)/IssuerHelper'

    - task: PublishPipelineArtifact@1
      displayName: "Upload pipeline test data"
      inputs:
        targetPath: $(System.DefaultWorkingDirectory)/Reports
        artifactName: issues-summary
        publishLocation: "pipeline"

    - task: Bash@3
      displayName: 'Set Script Executable'
      inputs:
        targetType: 'inline'
        script: |
          chmod +x $(System.DefaultWorkingDirectory)/eng/scripts/push-pipeline-result-markdown.sh

    - task: Bash@3
      displayName: 'Push commit about current pipeline status'
      inputs:
        targetType: 'filePath'
        filePath: '$(System.DefaultWorkingDirectory)/eng/scripts/push-pipeline-result-markdown.sh'
        arguments: >-
          $(GITHUB_PAT)
          $(GITHUB_OWNER)
          $(GITHUB_REPO)
          $(GIT_USER_NAME)
          $(GIT_USER_EMAIL)