name: Create a github issue to track pipeline result
trigger: none

pool:
  vmImage: ubuntu-latest

variables:
  GitHubPat: $(GITHUB_PAT)
  RepoOwner: $(REPO_OWNER)
  RepoName: $(REPO_NAME)

steps:
- task: Bash@3
  displayName: 'Create GitHub Issue'
  inputs:
    targetType: 'inline'
    script: |
      #!/bin/bash
      set -e

      URL="https://api.github.com/repos/$(RepoOwner)/$(RepoName)/issues"
      JSON='{
        "title": "Issue created by Azure DevOps Pipeline",
        "body": "This is the body of the issue created by Azure DevOps Pipeline.",
        "labels": ["bug"]
      }'

      response=$(curl -s -X POST -H "Authorization: token $(GitHubPat)" -H "Content-Type: application/json" -d "$JSON" "$URL")

      echo "Response from GitHub API:"
      echo "$response"