name: Create a github issue to track pipeline result
trigger: none

pool:
  vmImage: ubuntu-latest

parameters:
  - name: ServiceName
    type: string
    default: 'Search'
  - name: PackageName
    type: string
    default: 'azure-search-documents'

variables:
  GitHubPat: $(GITHUB_PAT)
  RepoOwner: $(REPO_OWNER)
  RepoName: $(REPO_NAME)

steps:
# - task: Bash@3
#   displayName: 'Set Script Executable'
#   inputs:
#     targetType: 'inline'
#     script: |
#       chmod +x $(Build.SourcesDirectory)/eng/common/create-github-issue.sh

# - task: Bash@3
#   displayName: 'Create GitHub Issue'
#   inputs:
#     targetType: 'filePath'
#     filePath: '$(Build.SourcesDirectory)/eng/common/create-github-issue.sh'
#     arguments: >-
#       ${{ parameters.PackageName }}
#       $(GitHubPat)
#       $(RepoOwner)
#       $(RepoName)
- task: DownloadPipelineArtifact@2
  inputs:
    buildType: 'specific'
    project: 'content-validation-automation'
    pipeline: 'Azure App Configuration'
    buildVersionToDownload: 'latestFromBranch'
    branchName: 'wenjie-dev'
    artifactName: 'TestResults'
    downloadPath: '$(System.DefaultWorkingDirectory)/Artifacts'