name: Run switched packages content validation
trigger: none

parameters:
- name: packages
  type: string
  default: 'azure-appconfiguration,azure-keyvault-keys'

jobs:
- ${{ each packageName in split(parameters.packages, ',') }}:
  - template: /eng/pipelines/${{ packageName }}.yml
    parameters:
      GitHubPat: $(GITHUB_PAT)
      GitHubOwner: $(GITHUB_OWNER)
      GitHubRepo: $(GITHUB_REPO)