parameters:
- name: GitHubPat
  type: string
  default: ''
- name: GitHubOwner
  type: string
  default: ''
- name: GitHubRepo
  type: string
  default: ''

jobs:
  - template: /eng/common/content-validation.yml
    parameters:
      ServiceName: 'App Configuration'
      PackageName: 'azure-appconfiguration'
      jobDisplayName: 'App_Configuration_Validation'
      DotNetSdkVersion: '8.0.x'
      Pipeline: 'Azure App Configuration'
      GitHubPat: ${{ parameters.GitHubPat }}
      GitHubOwner: ${{ parameters.GitHubOwner }}
      GitHubRepo: ${{ parameters.GitHubRepo }}
