name: Run azure-keyvault-certificates package content validation
trigger: none

pool:
  vmImage: ubuntu-latest

jobs:
  - template: /eng/common/content-validation.yml
    parameters:
      ServiceName: 'Key Vault'
      PackageName: 'azure-keyvault-certificates'
      DotNetSdkVersion: '8.0.x' 
