name: Run azure-ai-formrecognizer package content validation
trigger: none

pool:
  vmImage: ubuntu-latest

jobs:
  - template: /eng/common/content-validation.yml
    parameters:
      ServiceName: 'Cognitive Services'
      PackageName: 'azure-ai-formrecognizer'
      DotNetSdkVersion: '8.0.x' 
