name: Run azure-appconfiguration package content validation
trigger: none

extends:
  template: /eng/common/content-validation.yml

parameters:
- name: matrix
  type: object
  default:
    - ServiceName: 'App Configuration'
      PackageName: 'azure-appconfiguration'
    - ServiceName: 'Key Vault'
      PackageName: 'azure-keyvault-keys'   

jobs:
- ${{ each config in parameters.matrix }}:
  - template: /eng/common/content-validation.yml
    parameters:
      ServiceName: ${{ config.ServiceName }}
      PackageName: ${{ config.PackageName }}
      DotNetSdkVersion: '8.0.x'
      Pipeline: 'Azure App Configuration'
      GitHubPat: $(GITHUB_PAT)
      GitHubOwner: $(GITHUB_OWNER)
      GitHubRepo: $(GITHUB_REPO)
