name: Run azure-appconfiguration package content validation
trigger: none

variables:
- group: GitHubVariables

pool:
  vmImage: ubuntu-latest

jobs:
  - template: /eng/common/content-validation.yml
    parameters:
      ServiceName: 'App Configuration'
      PackageName: 'azure-appconfiguration'
      DotNetSdkVersion: '8.0.x' 
      GitHubPat: $(GITHUB_PAT)
      GitHubOwner: $(GITHUB_OWNER)
      GitHubRepo: $(GITHUB_REPO)
