name: Run azureml-featurestore package content validation
trigger: none

pool:
  vmImage: ubuntu-latest

jobs:
  - template: /eng/common/content-validation.yml
    parameters:
      ServiceName: 'Machine Learning'
      PackageName: 'azureml-featurestore'
      DotNetSdkVersion: '8.0.x' 
