parameters:
- name: GitHubPat
  type: string
  default: ''
- name: GitHubOwner
  type: string
  default: ''
- name: GitHubRepo
  type: string
  default: ''

jobs:
  - template: /eng/common/content-validation.yml
    parameters:
      ServiceName: 'Key Vault'
      PackageName: 'azure-keyvault-keys'
      jobDisplayName: 'Key_Vault_Validation'
      DotNetSdkVersion: '8.0.x'
      Pipeline: 'Azure KeyVault Keys'
      GitHubPat: ${{ parameters.GitHubPat }}
      GitHubOwner: ${{ parameters.GitHubOwner }}
      GitHubRepo: ${{ parameters.GitHubRepo }}