name: Run azure-iot-hub package content validation
trigger: none

pool:
  vmImage: ubuntu-latest

jobs:
  - template: /eng/common/content-validation.yml
    parameters:
      ServiceName: 'IoT'
      PackageName: 'azure-iot-hub'
      DotNetSdkVersion: '8.0.x' 
