name: Run azure-appconfiguration package content validation
trigger: none

parameters:
- name: matrix
  type: object
  default:
  - ServiceName: 'App Configuration'
    PackageName: 'azure-appconfiguration'
    jobDisplayName: 'App_Configuration_Validation'
  - ServiceName: 'Key Vault'
    PackageName: 'azure-keyvault-keys'
    jobDisplayName: 'Key_Vault_Validation'

jobs:
- ${{ each config in parameters.matrix }}:
  - template: /eng/common/content-validation.yml
    parameters:
      ServiceName: ${{ config.ServiceName }}
      PackageName: ${{ config.PackageName }}
      jobDisplayName: ${{ config.jobDisplayName }}
      DotNetSdkVersion: '8.0.x'
      Pipeline: 'Azure App Configuration'
      GitHubPat: $(GITHUB_PAT)
      GitHubOwner: $(GITHUB_OWNER)
      GitHubRepo: $(GITHUB_REPO)
