name: Run azure-ai-ml package content validation
trigger: none

pool:
  vmImage: ubuntu-latest

jobs:
  - template: /eng/common/content-validation.yml
    parameters:
      ServiceName: 'Machine Learning'
      PackageName: 'azure-ai-ml'
      DotNetSdkVersion: '8.0.x' 
