name: Run azure-appconfiguration package content validation
trigger: none

pool:
  vmImage: ubuntu-latest

jobs:
  - template: /eng/common/content-validation.yml
    parameters:
      ServiceName: 'App Configuration'
      PackageName: 'azure-appconfiguration'
      DotNetSdkVersion: '8.0.x' 
