name: Run Validation Rule Test Pipeline
trigger: none

parameters:
- name: DotNetSdkVersion  
  type: string

pool:
  vmImage: ubuntu-latest

steps:
- task: UseDotNet@2
  displayName: 'Install .NET Core SDK'
  inputs:
    packageType: 'sdk'
    version: ${{ parameters.DotNetSdkVersion }}
    installationPath: $(Agent.ToolsDirectory)/dotnet 

- task: DotNetCoreCLI@2
  displayName: New Manifest for tool
  inputs:
    command: custom
    custom: 'new '
    arguments: tool-manifest

- task: DotNetCoreCLI@2
  displayName: Install Playwright CLI
  inputs:
    command: custom
    custom: 'tool '
    arguments: install Microsoft.Playwright.CLI

- task: DotNetCoreCLI@2
  displayName: Run Playwright Install
  inputs:
    command: custom
    custom: 'tool '
    arguments: run playwright install

- task: DotNetCoreCLI@2
  displayName: Build ValidationRule.Test project
  inputs:
    command: 'build'
    projects: 'ValidationRule.Test/ValidationRule.Test.csproj'

- task: DotNetCoreCLI@2
  displayName: Run ValidationRule.Test case
  inputs:
    command: 'test'
    projects: 'ValidationRule.Test/ValidationRule.Test.csproj'
    arguments: '-e BROWSER=chromium'
    testRunTitle: 'ValidationRule.Test Testing Start'