parameters:
- name: AzureDevOpsPat
  type: string
  default: ''
- name: GitHubPat
  type: string
  default: ''
- name: GitHubOwner
  type: string
  default: ''
- name: GitHubRepo
  type: string
  default: ''
- name: packages
  type: string
  # default: 'azure-appconfiguration, azure-appconfiguration-provider, azure-security-attestation, azure-batch, azure-ai-contentsafety, azure-ai-formrecognizer, azure-ai-language-conversations, azure-ai-language-questionanswering, azure-ai-textanalytics, azure-ai-translation-document, azure-ai-translation-text, azure-cognitiveservices-language-spellcheck, azure-cognitiveservices-speech, azure-cognitiveservices-vision-contentmoderator, azure-cognitiveservices-vision-customvision, azure-healthinsights-radiologyinsights, azure-communication-callautomation, azure-communication-chat, azure-communication-email, azure-communication-identity, azure-communication-jobrouter, azure-communication-messages, azure-communication-phonenumbers, azure-communication-rooms, azure-communication-sms, azure-confidentialledger, azure-containerregistry, azure-cosmos, azure-developer-devcenter, azure-cognitiveservices-search-entitysearch, azure-eventgrid, azure-eventhub, azure-eventhub-checkpointstoreblob, azure-eventhub-checkpointstoreblob-aio, azure-functions, azure-functions-durable, azure-identity, azure-identity-broker, azure-cognitiveservices-search-imagesearch, azure-digitaltwins-core, azure-iot-device, azure-iot-deviceupdate, azure-iot-hub, azure-keyvault-administration, azure-keyvault-certificates, azure-keyvault-keys, azure-keyvault-secrets, azure-developer-loadtesting, azure-ai-ml, azureml-featurestore, azure-monitor-ingestion, azure-monitor-opentelemetry, azure-monitor-query, azure-cognitiveservices-search-newssearch, azure-schemaregistry, azure-schemaregistry-avroencoder, azure-search-documents, azure-servicebus, azure-servicefabric, azure-storage-blob, azure-storage-file-datalake, azure-storage-file-share, azure-storage-queue, azure-data-tables, azure-cognitiveservices-search-videosearch, azure-messaging-webpubsubclient, azure-messaging-webpubsubservice, azure-cognitiveservices-search-websearch, azure-core, uamqp, adal, azure-cosmosdb-table'
  default: 'azure-search-documents, azure-storage-blob, azure-storage-file-datalake, azure-storage-file-share, azure-storage-queue'

jobs:
- ${{ each packageName in split(parameters.packages, ',') }}:
  - template: /eng/pipelines/package/${{ packageName }}.yml
    parameters:
      GitHubPat: ${{ parameters.GitHubPat }}
      GitHubOwner: ${{ parameters.GitHubOwner }}
      GitHubRepo: ${{ parameters.GitHubRepo }}
      AzureDevOpsPat: ${{ parameters.AzureDevOpsPat }}
