
parameters:
- name: AzureDevOpsPat
  type: string
  default: ''
- name: GitHubPat
  type: string
  default: ''
- name: GitHubOwner
  type: string
  default: ''
- name: GitHubRepo
  type: string
  default: ''

jobs:
  - template: /eng/pipelines/common/content-validation.yml
    parameters:
      ServiceName: 'Web PubSub'
      PackageName: 'uamqp'
      jobDisplayName: 'UAMQP'
      DotNetSdkVersion: '8.0.x'
      GitHubPat: ${{ parameters.GitHubPat }}
      GitHubOwner: ${{ parameters.GitHubOwner }}
      GitHubRepo: ${{ parameters.GitHubRepo }}
      AzureDevOpsPat: ${{ parameters.AzureDevOpsPat }}
